### ISSUE TITLE
Using the API without running as root

### ISSUE THREAD

**Issue by OskarPersson** [gluster/libgfapi-python#12]
How can I use the API without running as root?

Using the example [here](http://libgfapi-python.readthedocs.io/en/latest/) in a file called foo.py I get the following results
```
$ python foo.py
Traceback (most recent call last):
  File "foo.py", line 5, in <module>
    volume.mount()
  File "/usr/local/lib/python2.7/dist-packages/gfapi-0.0.1-py2.7.egg/gluster/gfapi.py", line 563, in mount
    (self.fs, os.strerror(err)))
gluster.exceptions.LibgfapiException: glfs_init(42493440) failed: Transport endpoint is not connected

$ sudo python foo.py
Winter is coming.
```

**Comment by OskarPersson** [comment]
Solved it by following the steps provided [here].(https://thiagodasilvablog.wordpress.com/2014/01/31/how-to-mount-gluster-volume-using-libgfapi-as-non-root/)

> 1. Run the cli command: `sudo gluster volume set [volume_name] allow-insecure on`
2. Edit the file `glusterd.vol`: (usually placed under `/etc/glusterfs`)
    * add the line: `option rpc-auth-allow-insecure on`
3. Make sure to change permissions on the directory you are acessing to allow the appropriate non-root access
