### ISSUE TITLE
mount failed where used in Docker container

### ISSUE THREAD

**Issue by gfyulx** [gluster/libgfapi-python#25]
hi,
  when i used gfapi in docker container,it raise a os.strerror excepiton.
 here is the code and error message:
>>> volume=gfapi.Volume('192.168.6.151','aifs')
>>> volume.mount()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.6/lib/python3.6/site-packages/gluster/gfapi/gfapi.py", line 772, in mount
    (self.fs, os.strerror(err)))
gluster.gfapi.exceptions.LibgfapiException: glfs_init(31859440) failed: Invalid argument
 can anyone  help me?

**Comment by gfyulx** [comment]
i sloved this problem by add --privileged paramter when start the container
